### ISSUE TITLE
Unable to get dataset for korean scripts

### ISSUE THREAD

**Issue by xinshoulzc** [warnikchow/kosp2e#3]
I am trouble in getting zeroth datasets for korean scripts. I follow the steps in readme to send emails to this link (https://docs.google.com/forms/d/1UTpOrKIWK9uzngh7eIm-3oAp5b5vTdBj4ZapHj8cyBI/edit), but no response for several days.  For some research purposes, I want to apply my approaches to speech translations. I wonder if there are other ways to get this datasets. 
Thank you

**Comment by warnikchow** [comment]
Sorry for late reply! I think I didn't recognize the notification mail. Sorry for your inconvenience and please check your inbox :)
